### PR TITLE
opening quiz branch with pull request

### PR DESCRIPTION
**Pull request by debragordon**
opening PR

### CODE REVIEW

**Comment by debragordon** [comment]
@zoeames ready for review/thumbs up to merge.

Thanks for your help at the end of class!

**Comment by zoeames** [comment]
when i run your project i get the following error: "http://localhost:8080/lib/bower_components/bootstrap/dist/css/bootstrap.min.css Failed to load resource: the server responded with a status of 404 (Not Found)"
Looks like you are using bootstrap but it is not listed in your bower.json.  I should be able to run a bower install and have everything working.  did you forget the --save?

**Comment by debragordon** [comment]
I updated the bower.json and pushed it ... does that solve it??

**Comment by zoeames** [comment]
there are a few little bugs with the math but its not really a big deal and everything else looks good.  👍

**Pull request merged**
